name: proto-language-temp

channels:
  - pytorch # for pytorch-cuda metapackage
  - nvidia # for real CUDA libraries
  - conda-forge
  - defaults
  - bioconda

dependencies:
  # ─ core interpreter ─
  - python=3.11
  - pip

  # ─ GPU runtime ─
  - pytorch=2.6.0
  - pytorch-cuda=12.4

  # ─ scientific Python stack ─
  - numpy
  - pandas
  - requests
  - biopython
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - transformers
  - pytest

  # ─ interactive computing ─
  - ipykernel
  - ipywidgets

  # ─ bioinformatics ─
  - biotite
  - ipymol
  - py3Dmol
  - orfipy
  - mmseqs2

  # ─ pip-only packages ─
  - pip:
      - evo2

