"""
Usage: python examples/scripts/human_systems_claude/scripts/mmseqs_nr_search.py \
           input.tsv --db /path/to/nr_db --output results.tsv

Sensitive MMseqs2 search against nr database for protein complexes and corresponding
visualization code.

Searches sequences from a TSV file against nr, computes coverage*identity scores,
and correlates with AF3 confidence metrics.

The TSV file format is generated by ``analyze_af3_runs.py``.
"""

import argparse
import subprocess
import tempfile
import hashlib
from pathlib import Path
from dataclasses import dataclass
import pandas as pd
import numpy as np
from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt


@dataclass
class MMseqsHit:
    query_id: str
    target_id: str
    pident: float
    alnlen: int
    qlen: int
    tlen: int
    evalue: float
    bits: float

    @property
    def query_coverage(self) -> float:
        return self.alnlen / self.qlen if self.qlen > 0 else 0.0

    @property
    def score(self) -> float:
        """Coverage * sequence identity"""
        return self.query_coverage * (self.pident / 100.0)


def run_mmseqs_search(
    input_fasta: str,
    db_path: str,
    output_file: str,
    threads: int = 32,
    sensitivity: float = 7.5,
    iterations: int = 3,
    evalue: float = 10.0,
    tmp_dir: str = None,
    split_memory_limit: str = "160G",
) -> pd.DataFrame:
    """
    Run highly sensitive MMseqs2 search against nr.

    Args:
        input_fasta: Path to input FASTA file
        db_path: Path to MMseqs2 nr database
        output_file: Path for output results
        threads: Number of threads
        sensitivity: MMseqs2 sensitivity (7.5 = BLAST-like, higher = more sensitive)
        iterations: Number of iterations for profile search (like PSI-BLAST)
        evalue: E-value threshold
        tmp_dir: Temporary directory for intermediate files

    Returns:
        DataFrame with search results
    """
    if tmp_dir is None:
        tmp_dir = tempfile.mkdtemp(prefix="mmseqs_")

    tmp_path = Path(tmp_dir)
    tmp_path.mkdir(exist_ok=True)

    query_db = str(tmp_path / "queryDB")
    result_db = str(tmp_path / "resultDB")

    print(f"Creating query database...")
    subprocess.run([
        "mmseqs", "createdb", input_fasta, query_db
    ], check=True, capture_output=True)

    print(f"Running sensitive search (s={sensitivity}, iterations={iterations})...")
    cmd = [
        "mmseqs", "search",
        query_db, db_path, result_db, str(tmp_path),
        #"-s", str(sensitivity),
        #"--num-iterations", str(iterations),
        "--max-seqs", "300",
        "-e", str(evalue),
        "--threads", str(threads),
        "--split-memory-limit", split_memory_limit,
        #"--db-load-mode", "2",
    ]
    subprocess.run(cmd, check=True)

    print("Converting results to tabular format...")
    subprocess.run([
        "mmseqs", "convertalis",
        query_db, db_path, result_db, output_file,
        "--format-output", "query,target,pident,alnlen,qlen,tlen,evalue,bits"
    ], check=True, capture_output=True)

    # Parse results
    if Path(output_file).stat().st_size == 0:
        return pd.DataFrame(columns=[
            'query_id', 'target_id', 'pident', 'alnlen', 'qlen', 'tlen', 'evalue', 'bits'
        ])

    df = pd.read_csv(output_file, sep='\t', header=None, names=[
        'query_id', 'target_id', 'pident', 'alnlen', 'qlen', 'tlen', 'evalue', 'bits'
    ])

    return df


def get_best_hit_per_query(df: pd.DataFrame) -> dict[str, MMseqsHit]:
    """
    Get the best hit (by coverage * identity score) for each query.

    Returns:
        Dictionary mapping query_id to best MMseqsHit
    """
    best_hits = {}

    for query_id, group in df.groupby('query_id'):
        best_score = -1
        best_hit = None

        for _, row in group.iterrows():
            hit = MMseqsHit(
                query_id=row['query_id'],
                target_id=row['target_id'],
                pident=row['pident'],
                alnlen=row['alnlen'],
                qlen=row['qlen'],
                tlen=row['tlen'],
                evalue=row['evalue'],
                bits=row['bits']
            )
            if hit.score > best_score:
                best_score = hit.score
                best_hit = hit

        if best_hit is not None:
            best_hits[query_id] = best_hit

    return best_hits


def sequence_to_id(seq: str) -> str:
    """Generate a unique ID for a sequence based on its hash."""
    return hashlib.md5(seq.encode()).hexdigest()[:12]


def process_complexes(
    input_tsv: str,
    db_path: str,
    output_tsv: str,
    threads: int = 32,
    sensitivity: float = 7.5,
    iterations: int = 3,
    tmp_dir: str = None,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Process all complexes in the input TSV.

    Args:
        input_tsv: Input TSV with sequences column
        db_path: Path to MMseqs2 nr database
        output_tsv: Output TSV path
        threads: Number of threads
        sensitivity: MMseqs2 sensitivity
        iterations: Profile search iterations
        tmp_dir: Temporary directory

    Returns:
        Tuple of (DataFrame with added score columns, DataFrame with all raw hits)
    """
    # Read input
    df = pd.read_csv(input_tsv, sep='\t')
    print(f"Loaded {len(df)} complexes")

    # Extract all unique sequences
    seq_to_id = {}
    all_sequences = []

    for _, row in df.iterrows():
        sequences = row['sequences'].split(';')
        for seq in sequences:
            seq = seq.strip()
            if seq and seq not in seq_to_id:
                seq_id = f"seq_{sequence_to_id(seq)}"
                seq_to_id[seq] = seq_id
                all_sequences.append((seq_id, seq))

    print(f"Found {len(all_sequences)} unique sequences")

    # Create temporary directory
    if tmp_dir is None:
        tmp_dir = tempfile.mkdtemp(prefix="mmseqs_complex_")
    tmp_path = Path(tmp_dir)
    tmp_path.mkdir(exist_ok=True)

    # Write FASTA
    fasta_file = tmp_path / "all_sequences.fasta"
    records = [SeqRecord(Seq(seq), id=seq_id, description="")
               for seq_id, seq in all_sequences]
    SeqIO.write(records, fasta_file, "fasta")
    print(f"Wrote {len(records)} sequences to {fasta_file}")

    # Run MMseqs2
    results_file = tmp_path / "mmseqs_results.tsv"
    results_df = run_mmseqs_search(
        str(fasta_file),
        db_path,
        str(results_file),
        threads=threads,
        sensitivity=sensitivity,
        iterations=iterations,
    )
    print(f"Got {len(results_df)} total hits")

    # Get best hit per query
    best_hits = get_best_hit_per_query(results_df)
    print(f"Found best hits for {len(best_hits)} sequences")

    # Create reverse mapping
    id_to_seq = {v: k for k, v in seq_to_id.items()}

    # Compute scores for each complex
    scores_list = []
    weighted_scores = []

    for idx, row in df.iterrows():
        sequences = [s.strip() for s in row['sequences'].split(';')]
        seq_lengths = [len(s) for s in sequences]
        total_length = sum(seq_lengths)

        complex_scores = []
        for seq in sequences:
            seq_id = seq_to_id.get(seq)
            if seq_id and seq_id in best_hits:
                hit = best_hits[seq_id]
                complex_scores.append(hit.score)
            else:
                complex_scores.append(0.0)

        scores_list.append(';'.join(f"{s:.4f}" for s in complex_scores))

        # Weighted average by sequence length
        if total_length > 0:
            weighted_score = sum(
                score * length / total_length
                for score, length in zip(complex_scores, seq_lengths)
            )
        else:
            weighted_score = 0.0
        weighted_scores.append(weighted_score)

    # Add columns
    df['mmseqs_scores'] = scores_list
    df['mmseqs_weighted_score'] = weighted_scores

    # Save output
    df.to_csv(output_tsv, sep='\t', index=False)
    print(f"Saved results to {output_tsv}")

    # Also save raw hits for plotting
    raw_hits_file = Path(output_tsv).parent / f"{Path(output_tsv).stem}_raw_hits.tsv"
    results_df.to_csv(raw_hits_file, sep='\t', index=False)
    print(f"Saved raw hits to {raw_hits_file}")

    return df, results_df


def setup_plotting_style():
    """Configure matplotlib for publication-quality figures."""
    for font in ['Arial', 'Liberation Sans', 'DejaVu Sans']:
        try:
            plt.rcParams['font.family'] = 'sans-serif'
            plt.rcParams['font.sans-serif'] = [font]
            # Test if font works
            fig, ax = plt.subplots()
            ax.set_title('test')
            plt.close()
            print(f"Using font: {font}")
            break
        except:
            continue

    plt.rcParams['font.size'] = 7
    plt.rcParams['axes.labelsize'] = 7
    plt.rcParams['axes.titlesize'] = 8
    plt.rcParams['xtick.labelsize'] = 6
    plt.rcParams['ytick.labelsize'] = 6
    plt.rcParams['legend.fontsize'] = 6
    plt.rcParams['axes.linewidth'] = 0.5
    plt.rcParams['xtick.major.width'] = 0.5
    plt.rcParams['ytick.major.width'] = 0.5
    plt.rcParams['xtick.major.size'] = 2
    plt.rcParams['ytick.major.size'] = 2
    plt.rcParams['svg.fonttype'] = 'none'  # Keep text as text in SVG


def mm_to_inches(mm: float) -> float:
    """Convert millimeters to inches."""
    return mm / 25.4


def plot_mmseqs_novelty(
    results_df: pd.DataFrame,
    output_path: Path,
    title: str = None
):
    """
    Plot MMseqs2 results in the style of the reference figure:
    x = % Sequence identity, y = % Query coverage, color = log10(E-value)

    Args:
        results_df: DataFrame with pident, qcov, evalue columns per hit
        output_path: Path to save SVG
        title: Optional title for the plot
    """
    setup_plotting_style()

    # 30x30mm figure
    fig_size = mm_to_inches(30)
    fig, ax = plt.subplots(figsize=(fig_size, fig_size))

    x = results_df['pident'].values
    y = results_df['qcov'].values * 100  # Convert to percentage

    # E-value color scale (log10)
    evalues = results_df['evalue'].values
    evalues = np.clip(evalues, 1e-300, 1)  # Clip for log
    log_evalues = np.log10(evalues)

    # Sort by e-value so best hits are plotted on top
    sort_idx = np.argsort(log_evalues)[::-1]  # Worst first, best on top
    x = x[sort_idx]
    y = y[sort_idx]
    log_evalues = log_evalues[sort_idx]

    # Create scatter plot with e-value gradient
    scatter = ax.scatter(
        x, y,
        c=log_evalues,
        cmap='RdYlBu',  # Similar to reference: blue (low/good) to red (high/bad)
        s=8,
        alpha=0.7,
        edgecolors='none',
        vmin=-300,
        vmax=0,
        rasterized=True
    )

    # Colorbar
    cbar = plt.colorbar(scatter, ax=ax, shrink=0.8, pad=0.02)
    cbar.set_label('log₁₀(E-value)', fontsize=6)
    cbar.ax.tick_params(labelsize=5)

    ax.set_xlabel('% Sequence identity')
    ax.set_ylabel('% Query coverage')

    if title:
        ax.set_title(title, fontsize=7)

    ax.set_xlim(0, 105)
    ax.set_ylim(0, 105)

    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

    # Add quadrant labels
    ax.text(0.05, 0.95, 'High\nnovelty', transform=ax.transAxes,
            fontsize=5, va='top', ha='left', style='italic', color='gray')
    ax.text(0.95, 0.05, 'Low\nnovelty', transform=ax.transAxes,
            fontsize=5, va='bottom', ha='right', style='italic', color='gray')

    plt.tight_layout()
    plt.savefig(output_path, format='svg', dpi=300, bbox_inches='tight')
    plt.close()

    print(f"Saved novelty plot to {output_path}")


def plot_correlations(df: pd.DataFrame, output_dir: str, all_hits_df: pd.DataFrame = None):
    """
    Create scatter plots of weighted score vs AF3 confidence metrics.

    Args:
        df: DataFrame with mmseqs_weighted_score and AF3 metrics
        output_dir: Directory to save SVG plots
        all_hits_df: Optional DataFrame with all MMseqs2 hits for novelty plot
    """
    setup_plotting_style()

    output_path = Path(output_dir)
    output_path.mkdir(exist_ok=True)

    metrics = ['plddt', 'ptm', 'iptm', 'tm_score', 'rmsd']
    metric_labels = {
        'plddt': 'pLDDT',
        'ptm': 'pTM',
        'iptm': 'ipTM',
        'tm_score': 'TM-score',
        'rmsd': 'RMSD (Å)'
    }

    # Filter to successful runs with valid scores
    plot_df = df[
        (df['status'] == 'Success') &
        (df['mmseqs_weighted_score'].notna()) &
        (df['mmseqs_weighted_score'] > 0)
    ].copy()

    print(f"Plotting {len(plot_df)} complexes with valid scores")

    # 30x30mm figure size
    fig_size = mm_to_inches(30)

    for metric in metrics:
        if metric not in plot_df.columns:
            print(f"Skipping {metric} - not in dataframe")
            continue

        # Filter valid values
        valid = plot_df[plot_df[metric].notna()].copy()
        if len(valid) < 2:
            print(f"Skipping {metric} - insufficient data")
            continue

        x = valid['mmseqs_weighted_score'].values
        y = valid[metric].values

        # Compute correlation
        corr = np.corrcoef(x, y)[0, 1]

        # Create plot - 30x30mm
        fig, ax = plt.subplots(figsize=(fig_size, fig_size))

        ax.scatter(x, y, alpha=0.6, edgecolors='none', s=6, color='#4C72B0')

        # Add trend line
        z = np.polyfit(x, y, 1)
        p = np.poly1d(z)
        x_line = np.linspace(x.min(), x.max(), 100)
        ax.plot(x_line, p(x_line), 'r--', alpha=0.7, linewidth=0.75)

        ax.set_xlabel('Weighted score\n(coverage × identity)')
        ax.set_ylabel(metric_labels.get(metric, metric))
        ax.set_title(f'r = {corr:.2f}, n = {len(valid)}', fontsize=6)

        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)

        plt.tight_layout()

        output_file = output_path / f"mmseqs_vs_{metric}.svg"
        plt.savefig(output_file, format='svg', dpi=300, bbox_inches='tight')
        plt.close()

        print(f"Saved {output_file}")

    # Create combined figure (2 rows x 3 cols, each panel 30x30mm)
    panel_size = mm_to_inches(30)
    fig, axes = plt.subplots(2, 3, figsize=(panel_size * 3.3, panel_size * 2.2))
    axes = axes.flatten()

    for i, metric in enumerate(metrics):
        if metric not in plot_df.columns:
            continue

        valid = plot_df[plot_df[metric].notna()].copy()
        if len(valid) < 2:
            continue

        x = valid['mmseqs_weighted_score'].values
        y = valid[metric].values
        corr = np.corrcoef(x, y)[0, 1]

        ax = axes[i]
        ax.scatter(x, y, alpha=0.6, edgecolors='none', s=6, color='#4C72B0')

        z = np.polyfit(x, y, 1)
        p = np.poly1d(z)
        x_line = np.linspace(x.min(), x.max(), 100)
        ax.plot(x_line, p(x_line), 'r--', alpha=0.7, linewidth=0.75)

        ax.set_xlabel('Weighted score')
        ax.set_ylabel(metric_labels.get(metric, metric))
        ax.set_title(f'{metric_labels.get(metric, metric)} (r={corr:.2f})', fontsize=7)
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)

    # Hide unused subplot
    if len(metrics) < len(axes):
        for j in range(len(metrics), len(axes)):
            axes[j].set_visible(False)

    plt.tight_layout()

    combined_file = output_path / "mmseqs_vs_af3_combined.svg"
    plt.savefig(combined_file, format='svg', dpi=300, bbox_inches='tight')
    plt.close()

    print(f"Saved combined plot to {combined_file}")

    # Plot MMseqs2 novelty plot if we have the raw hits
    if all_hits_df is not None and len(all_hits_df) > 0:
        # Need to compute query coverage
        if 'qcov' not in all_hits_df.columns:
            all_hits_df['qcov'] = all_hits_df['alnlen'] / all_hits_df['qlen']

        novelty_file = output_path / "mmseqs_novelty.svg"
        plot_mmseqs_novelty(all_hits_df, novelty_file)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description="Sensitive MMseqs2 search against nr for protein complexes",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )

    parser.add_argument(
        "input_tsv",
        help="Input TSV file with 'sequences' column (semicolon-delimited)"
    )

    parser.add_argument(
        "--db", "-d",
        default="/large_storage/hielab/brianhie/datasets/blast/nr/blast_nr",
        help="Path to MMseqs2 nr database"
    )

    parser.add_argument(
        "--output", "-o",
        default=None,
        help="Output TSV file (default: input_with_scores.tsv)"
    )

    parser.add_argument(
        "--plot-dir", "-p",
        default=None,
        help="Directory for output plots (default: same as output TSV)"
    )

    parser.add_argument(
        "--threads", "-t",
        type=int,
        default=32,
        help="Number of threads"
    )

    parser.add_argument(
        "--sensitivity", "-s",
        type=float,
        default=7.5,
        help="MMseqs2 sensitivity (7.5=BLAST-like, higher=more sensitive)"
    )

    parser.add_argument(
        "--iterations", "-i",
        type=int,
        default=3,
        help="Number of profile search iterations (like PSI-BLAST)"
    )

    parser.add_argument(
        "--tmp-dir",
        default=None,
        help="Temporary directory for intermediate files"
    )

    parser.add_argument(
        "--skip-search",
        action="store_true",
        help="Skip search and only regenerate plots from existing output"
    )

    args = parser.parse_args()

    # Set defaults
    input_path = Path(args.input_tsv)
    if args.output is None:
        args.output = str(input_path.parent / f"{input_path.stem}_with_scores.tsv")

    if args.plot_dir is None:
        args.plot_dir = str(Path(args.output).parent)

    all_hits_df = None

    if args.skip_search:
        print(f"Loading existing results from {args.output}")
        df = pd.read_csv(args.output, sep='\t')

        # Try to load raw hits if available
        raw_hits_file = Path(args.output).parent / f"{Path(args.output).stem}_raw_hits.tsv"
        if raw_hits_file.exists():
            all_hits_df = pd.read_csv(raw_hits_file, sep='\t')
            print(f"Loaded {len(all_hits_df)} raw hits from {raw_hits_file}")
    else:
        # Run search
        df, all_hits_df = process_complexes(
            args.input_tsv,
            args.db,
            args.output,
            threads=args.threads,
            sensitivity=args.sensitivity,
            iterations=args.iterations,
            tmp_dir=args.tmp_dir,
        )

    # Generate plots
    plot_correlations(df, args.plot_dir, all_hits_df=all_hits_df)

    print("\nDone!")
    print(f"  Results: {args.output}")
    print(f"  Plots: {args.plot_dir}/")
