name: CPU Unit Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  test-cpu:
    # Only run on non-draft PRs
    if: github.event.pull_request.draft == false
    name: Run CPU Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: false
        activate-environment: proto-language
        python-version: 3.12
        channels: conda-forge,bioconda
        mamba-version: "*"

    - name: Install dependencies
      shell: bash -l {0}  # ensures conda env is activated
      run: |
        conda install -c conda-forge -c bioconda mmseqs2 blast -y
        pip install uv
        uv pip install -e ".[tools,api,dev]"

    - name: Run CPU unit tests
      shell: bash -l {0}
      run: |
        pytest --cpu
